project_id = "hntqjlgfixmjsihsrdxd"

[functions.create-admin-user]
verify_jwt = false

[functions.admin-reset-employee-password]
verify_jwt = true

[functions.admin-delete-employee]
verify_jwt = true

[functions.compliance-automation]
verify_jwt = false

[functions.compliance-data-archival]
verify_jwt = false

[functions.compliance-notifications]
verify_jwt = false

[functions.generate-statement-pdf]
verify_jwt = false